version: '3'

services:
  postgis:
    image: piensg017.ensg.eu:5000/rpi-postgresql-postgis:latest # based on tobi312/rpi-postgresql-postgis 
    ports:
      - "5432:5432"
    volumes:
      - /mnt/Data/postgresql:/var/lib/postgresql/data 
    environment:
      - "POSTGRES_PASSWORD=docker"
