version: "2.0"
services:
  nginx:
    image: akkerman/rpi-nginx
    volumes:
      - /mnt/data/nginx/data/:/etc/nginx/conf.d/mysite.template
      - /mnt/data/nginx/log/:/opt/nginx/log/
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
      - TRAEFIK_LOG_LEVEL="INFO"
      - TRAEFIK_LOG_FILE="/opt/nginx/log/nginx.log"
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
