version: "2.0"
services:
  frontlb:
    image: hypriot/rpi-traefik
    command: --web --docker --docker.domain=piensg011.ensg.eu
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - "80:80"
     - "8080:8080"
