version: "2.0"
services:
  frontlb:
    image: hypriot/rpi-traefik
    command: --web --docker --docker.domain=piensg017.ensg.eu
    environment:
     - TRAEFIK_LOG_LEVEL="INFO"
     - TRAEFIK_LOG_FILE="/opt/traefik/log/traefik.log"
     - TRAEFIK_ACCESS_FILE="/opt/traefik/log/access.log"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /mnt/data/traefik/log/:/opt/traefik/log/
    ports:
     - "80:80"
     - "8080:8080"
