version: '3'

services:
  proftpd:
    image: piensg017.ensg.eu:5000/ftp:latest
    volumes:
      - /mnt/Data/ftp/livraison:/data
      - /mnt/Data/ftp/config:/proftpd
    ports:
      - "21:21"
      - "5001-5051:5001-5051"
