
version: '2'
services:
  rok4: 
    image: rok4/rok4:arm-http
    # Exposed ports cannot be accessed publicly over the internet. (published ports are !)
    # Actual port should match front-end and docker swarm config
    ports: 
      - 8080:80
    volumes:
      - /mnt/Data/geodata/scan1000:/rok4/config/pyramids/scan1000
      - /mnt/Data/geodata/bdortho:/rok4/config/pyramids/bdortho
    

