version: '3'

services:
  rok4:
    image: piensg017.ensg.eu:5000/rok4:arm-http
    volumes:
      - /mnt/Data/geodata/scan1000:/rok4/config/pyramids/scan1000
      - /mnt/Data/geodata/bdortho:/rok4/config/pyramids/bdortho
#Partie à ajouter pour que le service se "déclare" auprès de traefik
    networks:
      - INTERCO
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:172.31.56.158,piensg017.ensg.eu;Path:/rok4"
        - "traefik.backend=rok4"

networks:
  INTERCO:
    external: true
