version: '3'

services:
  rok4:
    image: piensg017.ensg.eu:5000/rok4:arm-http
    ports:
      - 8092:80
    volumes:
      - /mnt/Data/geodata/scan1000:/rok4/config/pyramids/scan1000
      - /mnt/Data/geodata/bdortho:/rok4/config/pyramids/bdortho
